on:
  workflow_dispatch:
    inputs:
      buildFlavor:
        type: choice
        options:
          - develop
          - staging
        default: 'develop'
        description: 'Build Flavor'
      buildType:
        type: choice
        options:
          - debug
          - release
        default: 'debug'
        description: 'Build Type'

jobs:
#  build:
#    name: Build and upload APK [DEV]
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          distribution: temurin
#          java-version: 17
#
#      - name: Assemble debug APK
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: assembleDebug --stacktrace
#          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/staging' && github.ref != 'refs/heads/develop' }}
#
#      - name: Upload APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: app-${{ inputs.buildType }}
#          path: app/build/outputs/apk/debug/app-debug.apk
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Env: ${{ github.event.inputs.buildFlavor }}" 
          echo "Branch: ${{ github.event.inputs.buildType }}"
